In [49]:
import sqlite3
import pandas as pd

In [63]:
conn=sqlite3.connect('./db/wsc.db')
conn.row_factory = lambda cursor, row: {col[0] : row[i] for i,col in enumerate(cursor.description)}

In [ ]:
query="""SELECT v.id_reference_produit,SUM(v.quantite) AS quantite_total,p.prix AS prix_unitaire,SUM(p.prix*quantite) AS prix_total
FROM vente AS v
LEFT JOIN produit AS p 
ON v.id_reference_produit=p.id_reference_produit
GROUP BY v.id_reference_produit

"""

cur=conn.cursor()
res=cur.execute(query)
result=res.fetchall()

In [50]:
df= pd.DataFrame(result)

In [51]:
df.head()

  id_reference_produit  quantite_total  prix_unitaire  prix_total
0               REF001              24          49.99     1199.76
1               REF002              27          19.99      539.73
2               REF003              15          29.99      449.85
3               REF004              21          79.99     1679.79
4               REF005              35          39.99     1399.65

In [48]:
print(result)

[{'id_reference_produit': 'REF001', 'quantite_total': 24, 'prix_unitaire': 49.99, 'prix_total': 1199.76}, {'id_reference_produit': 'REF002', 'quantite_total': 27, 'prix_unitaire': 19.99, 'prix_total': 539.73}, {'id_reference_produit': 'REF003', 'quantite_total': 15, 'prix_unitaire': 29.99, 'prix_total': 449.85}, {'id_reference_produit': 'REF004', 'quantite_total': 21, 'prix_unitaire': 79.99, 'prix_total': 1679.79}, {'id_reference_produit': 'REF005', 'quantite_total': 35, 'prix_unitaire': 39.99, 'prix_total': 1399.65}]

In [65]:
def analysis(conn,file_path):
    """Cette fonction permet d'éxecuter uner requête SQL à partir d'un fichier dans la base de donnée
    elle retourne un dataframe
    """

    #création du cursor
    c=conn.cursor()
    # Lecture du fichier
    fd=open(file_path,'r')
    query=fd.read()
    fd.close()
    # execution de la requête
    res=c.execute(query)
    #resultat à partir du cursor avec fetchall
    result=res.fetchall()
    #transformation du resultat en dataframe
    
    df=pd.DataFrame(result)
    

    return df

In [79]:
df=analysis(conn, '/home/olivierpi/wild_code_school/wcs-sales-project/sql/total_ca.sql')

In [80]:
df.head()

   chiffre_affaire_total
0                5268.78

In [78]:
with open('/home/olivierpi/wild_code_school/wcs-sales-project/sql/total_ca.sql', 'r') as f:
    print(repr(f.read()))

'SELECT SUM(p.prix*v.quantite) AS chiffre_affaire_total\nFROM vente AS v\nLEFT JOIN produit AS p ON v.id_reference_produit=p.id_reference_produit\n\n\n\n'